name: Deploy Laravel Project to cPanel via FTP

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.0

    - name: Install Composer dependencies
      run: composer install --no-progress --no-interaction --prefer-dist --optimize-autoloader

    - name: Build assets
      run: npm install && npm run production

    - name: Deploy via FTP
      uses: SamKirkland/FTP-Deploy-Action@4.2.0
      with:
        ftp-server: ${{ secrets.FTP_SERVER }}
        ftp-username: ${{ secrets.FTP_USERNAME }}
        ftp-password: ${{ secrets.FTP_PASSWORD }}
        local-dir: .
        server-dir: /
